services:
    app:
        build:
            args:
                user: ${USER:-www-data}
                uid: ${UID:-1000}
                group: ${GROUP:-1000}
            context: .
            dockerfile: .docker/app.dockerfile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped
        container_name: ${PROJECT_NAME}-app
        ports:
            - 5173:5173
        volumes:
            - .:/var/www/html:delegated
            - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        networks:
            - network
    nginx:
        image: nginx:1.17-alpine
        restart: unless-stopped
        container_name: ${PROJECT_NAME}-nginx
        depends_on:
            - app
        ports:
            - "${WEB_PORT:-8080}:80"
        volumes:
            - .:/var/www/html
            - ./.docker/nginx:/etc/nginx/conf.d
            - ./.docker/nginx/log:/var/log/nginx
            # - ./.docker/cert:/etc/letsencrypt
        networks:
            - network
networks:
    network:
        driver: bridge
